In [2]:
from pycaret.classification import *
import pandas as pd
import os
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeClassifier
import lightgbm as lgb

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import cross_validate
from sklearn.inspection import permutation_importance
from sklearn.tree import DecisionTreeClassifier


from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
data_path = '/Users/sola/Downloads/open/'
train = pd.read_csv(data_path + 'train.csv')
test = pd.read_csv(data_path + 'test.csv')
submission = pd.read_csv(data_path + 'sample_submission.csv')
train_x = train.drop(['TIMESTAMP', 'PRODUCT_ID','LINE','PRODUCT_CODE','Y_Class','Y_Quality'], axis=1)
train_y = train['Y_Class']

In [4]:
!pip install xgboost

In [5]:
from xgboost import XGBClassifier
X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.4, random_state=42)

# model = XGBClassifier(tree_method='hist', random_state=42)
model = lgb.LGBMClassifier(random_state=42)
model.fit(X_train, y_train)
prediction = model.predict(X_test)

print(confusion_matrix(prediction, y_test))
print(f"A_정답률:{accuracy_score(prediction, y_test):.3f}")

[[ 10   4   1]
 [ 29 144  23]
 [  1   9  19]]
A_정답률:0.721


In [6]:
test_x = test.drop(['TIMESTAMP', 'PRODUCT_ID','LINE','PRODUCT_CODE'], axis=1)
preds = model.predict(test_x)

In [7]:
preds

array([1, 1, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [8]:
submit = pd.read_csv('/Users/sola/Downloads/open/sample_submission.csv')

In [9]:
submit['Y_Class'] = preds

In [10]:
submit.to_csv('/Users/sola/Downloads/open/baseline_submission13.csv', index=False)

submit13 10R~ lgb로 돌렸는데 정확도 왜이래;; 걍 주글래~~~
0.4545650301

submit14 쌩으로 xgboost써서 돌려봤는데 정확도 ㄷㄷ;; 주글래~~ㅎㅎ
0.529262777